import{describe,it,expect}from'vitest';import{mkdtemp,writeFile,readFile,chmod,realpath,symlink,lstat}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{connect}from'@thenavidm/slipway/testing';import{loadConfig}from'../src/config.js';import{BrandfetchClient}from'../src/api/client.js';import{createApp}from'../src/app.js';import{ALL_TOOLS,OPERATIONS,compileAll,validateArguments}from'../src/tools/index.js';
const env={BRANDFETCH_API_KEY:'fixture-api-secret',BRANDFETCH_CLIENT_ID:'fixture-client',BRANDFETCH_MIN_REQUEST_INTERVAL_MS:'0'};const assetSrc='https://cdn.brandfetch.io/id_fixture/theme/dark/logo.svg?c=fixture-asset-secret';
const data={name:'Example',domain:'example.test',colors:[{hex:'#123456',type:'accent'}],fonts:[{name:'Fixture Sans',type:'title'}],logos:[{type:'logo',theme:'dark',formats:[{src:assetSrc,format:'svg'}]}]};
async function setup(extra:Record<string,string>={},reply:(url:URL,options:RequestInit)=>Response|Promise<Response>=()=>new Response(JSON.stringify(data),{status:200})){const calls:{url:URL;options:RequestInit}[]=[];const config=loadConfig({...env,...extra});const api=new BrandfetchClient(config,(async(url:any,options:any)=>{const u=new URL(String(url));calls.push({url:u,options});return reply(u,options);})as typeof fetch);const mcp=await connect(createApp({context:()=>({config,client:api})}),{env:{...env,...extra}});return{api,mcp,calls,close:()=>mcp.close()};}
// The exit code the CLI gives for an error: Slipway's code for it decides, so the MCP result carries it too.
const exitCodeFor=(value:{code?:string})=>({usage:2,refused:2,not_found:3,auth:4,api:5,timeout:5,rate_limited:7,not_configured:10} as Record<string,number>)[value.code??'']??1;
// A call to a hidden tool is a protocol error rather than a tool result; both are refusals a client sees.
const call=async(s:Awaited<ReturnType<typeof setup>>,name:string,args:any)=>{try{const r=await s.mcp.callTool(name,args);return{error:!!r.isError,value:JSON.parse((r.content as any)[0].text)};}catch(e){return{error:true,value:{error:(e as Error).message,code:'usage'}};}};
const native=(name:string)=>ALL_TOOLS.find(t=>t.name===name)!;
describe('current provider contract and private profiles',()=>{
 it('has 11 supported native operations and preserves all seven legacy names',()=>{expect(OPERATIONS).toHaveLength(11);expect(ALL_TOOLS).toHaveLength(14);for(const n of['search_brands','get_brand','get_brand_colors','get_brand_fonts','get_logo_url','download_brand_logos','compare_brands'])expect(native(n)).toBeTruthy();expect(OPERATIONS.every(o=>!o.path.includes('agents'))).toBe(true);});
 it('encodes URL identifiers in a fixed provider path without following caller origins',async()=>{const s=await setup();try{expect((await call(s,'get_brand',{identifier:'https://example.test/path?x=1'})).error).toBe(false);expect(s.calls[0].url.origin).toBe('https://api.brandfetch.io');expect(s.calls[0].url.pathname).toBe('/v2/brands/https%3A%2F%2Fexample.test%2Fpath%3Fx%3D1');expect(s.calls[0].options.redirect).toBe('error');expect(s.calls[0].options.signal).toBeTruthy();}finally{await s.close();}});
 it('uses an explicit route and preserves false native query booleans',async()=>{const s=await setup();try{await call(s,'get_brand',{identifier:'BTC',identifier_type:'crypto',cachedOnly:false,allowNsfw:false});expect(s.calls[0].url.pathname).toBe('/v2/brands/crypto/BTC');expect(s.calls[0].url.searchParams.get('cachedOnly')).toBe('false');expect(s.calls[0].url.searchParams.get('allowNsfw')).toBe('false');}finally{await s.close();}});
 it('search uses profile client ID and never forwards its Brand API key',async()=>{const s=await setup();try{await call(s,'search_brands',{query:'A & B'});expect(s.calls[0].url.pathname).toBe('/v2/search/A%20%26%20B');expect(s.calls[0].url.searchParams.get('c')).toBe('fixture-client');expect((s.calls[0].options.headers as any).Authorization).toBeUndefined();}finally{await s.close();}});
 it('client-ID-only setup can search but fails Brand API reads locally',async()=>{const s=await setup({BRANDFETCH_API_KEY:''});try{expect((await call(s,'search_brands',{query:'Example'})).error).toBe(false);const r=await call(s,'get_brand',{identifier:'example.test'});expect(r.error).toBe(true);expect(exitCodeFor(r.value)).toBe(10);expect(s.calls).toHaveLength(1);}finally{await s.close();}});
 it('named profiles never inherit global keys or client IDs',async()=>{const s=await setup({BRANDFETCH_ACCOUNTS:JSON.stringify([{name:'A',api_key:'fixture-A',client_id:'client-A'},{name:'B'}])});try{const r=await call(s,'get_brand',{identifier:'example.test',account:'B'});expect(exitCodeFor(r.value)).toBe(10);const r2=await call(s,'search_brands',{query:'Example',account:'B'});expect(exitCodeFor(r2.value)).toBe(10);expect(s.calls).toHaveLength(0);await call(s,'get_brand',{identifier:'example.test',account:'A'});expect((s.calls[0].options.headers as any).Authorization).toBe('Bearer fixture-A');}finally{await s.close();}});
 it('unknown profile makes no request',async()=>{const s=await setup();try{const r=await call(s,'get_brand',{identifier:'example.test',account:'other'});expect(exitCodeFor(r.value)).toBe(10);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('rejects malformed config, duplicate profile names and unknown default',()=>{for(const x of[{BRANDFETCH_ACCOUNTS:'{}'},{BRANDFETCH_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'},{BRANDFETCH_DEFAULT_ACCOUNT:'missing'},{BRANDFETCH_API_KEY:'a\nb'},{BRANDFETCH_REQUEST_TIMEOUT_MS:'NaN'}])expect(()=>loadConfig({...env,...x})).toThrow();});
 it('private token file is preferred and cached per client',async()=>{const dir=await realpath(await mkdtemp(join(tmpdir(),'brandfetch-key-')));const file=join(dir,'key');await writeFile(file,'fixture-file-key',{mode:0o600});const s=await setup({BRANDFETCH_TOKEN_FILE:file});try{await call(s,'get_viewer',{});await writeFile(file,'rotated');await call(s,'get_viewer',{});expect(s.calls.map(c=>(c.options.headers as any).Authorization)).toEqual(['Bearer fixture-file-key','Bearer fixture-file-key']);}finally{await s.close();}});
 it.skipIf(process.platform==='win32')('refuses a symlink token file before network',async()=>{const dir=await realpath(await mkdtemp(join(tmpdir(),'brandfetch-link-')));const target=join(dir,'key'),link=join(dir,'link');await writeFile(target,'key',{mode:0o600});await symlink(target,link);const s=await setup({BRANDFETCH_TOKEN_FILE:link});try{expect((await call(s,'get_viewer',{})).error).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it.skipIf(process.platform==='win32')('refuses a broadly readable token on POSIX',async()=>{if(process.platform==='win32')return;const dir=await realpath(await mkdtemp(join(tmpdir(),'brandfetch-perms-'))),file=join(dir,'key');await writeFile(file,'key',{mode:0o644});await chmod(file,0o644);const s=await setup({BRANDFETCH_TOKEN_FILE:file});try{expect((await call(s,'get_viewer',{})).error).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('reports cached 204 miss without pretending there is brand data',async()=>{const s=await setup({},()=>new Response(null,{status:204}));try{const r=await call(s,'get_brand',{identifier:'missing.test',cachedOnly:true});expect(r.value).toEqual({status:204,cachedMiss:true,data:null});}finally{await s.close();}});
 it('transaction descriptor has exact native JSON keys and is not a payment',async()=>{const s=await setup();try{await call(s,'enrich_transaction',{transaction_label:'FIXTURE CAFE',country_code:'US'});expect(s.calls[0].options.method).toBe('POST');expect(JSON.parse(s.calls[0].options.body as string)).toEqual({transactionLabel:'FIXTURE CAFE',countryCode:'US'});expect(s.calls[0].url.pathname).toBe('/v2/brands/transaction');}finally{await s.close();}});
 it('validates explicit identifiers, country and unknown arguments before fetch',async()=>{const s=await setup();try{for(const[n,a]of[['get_brand',{identifier:'../'}],['get_brand',{identifier:'.'}],['get_brand',{identifier:'https://example.test',identifier_type:'domain'}],['get_brand',{identifier:'x',unknown:1}],['enrich_transaction',{transaction_label:'x',country_code:'usa'}]]as const){expect((await call(s,n,a)).error).toBe(true);}expect(s.calls).toHaveLength(0);}finally{await s.close();}});
});
describe('shared safeguards and useful local workflows',()=>{
 it('compiles every input and native schema with the native validator',()=>expect(compileAll()).toBeGreaterThan(ALL_TOOLS.length));
 it('read-only hides both writes, so a direct call finds nothing to run',async()=>{const s=await setup({BRANDFETCH_READ_ONLY:'1'});try{const tools=await s.mcp.listTools();expect(tools).toHaveLength(12);for(const[n,a]of[['prefetch_brand',{identifier:'example.test',confirm:true}],['download_brand_logos',{identifier:'example.test',output_dir:'/not-used',confirm:true}]]as const){const r=await call(s,n,a);expect(r.error).toBe(true);expect(r.value.error).toMatch(/READ_ONLY|not found/);}expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('prefetch requires confirmation and returns native HEAD 202 without JSON parsing',async()=>{const s=await setup({},()=>new Response(null,{status:202,headers:{'retry-after':'3'}}));try{expect((await call(s,'prefetch_brand',{identifier:'example.test'})).error).toBe(true);expect(s.calls).toHaveLength(0);const r=await call(s,'prefetch_brand',{identifier:'example.test',confirm:true});expect(r.value).toEqual({status:202,crawlQueued:true,indexed:false,retryAfter:'3'});expect(s.calls).toHaveLength(1);expect(s.calls[0].options.method).toBe('HEAD');}finally{await s.close();}});
 it('disabled mutations refuse confirmed execution',async()=>{const s=await setup({BRANDFETCH_ALLOW_DESTRUCTIVE:'0'});try{expect((await call(s,'prefetch_brand',{identifier:'example.test',confirm:true})).error).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('returns only colors or fonts without leaking private asset credentials',async()=>{const s=await setup();try{const r=await call(s,'get_brand_colors',{identifier:'example.test'});expect(r.value).toEqual({name:data.name,domain:data.domain,colors:data.colors});const full=await call(s,'get_brand',{identifier:'example.test'});expect(JSON.stringify(full)).not.toContain('fixture-asset-secret');expect(JSON.stringify(full)).not.toContain('fixture-api-secret');}finally{await s.close();}});
 it('constructs browser URLs with separate identifier and asset types and no request',async()=>{const s=await setup();try{const r=await call(s,'get_logo_url',{identifier:'BTC',identifier_type:'crypto',icon:true,width:200});expect(r.value.url).toContain('/crypto/BTC/w/200/fallback/404/type/icon?c=fixture-client');expect(r.value.browserDisplayOnly).toBe(true);expect(r.value.programmaticDownloadAllowed).toBe(false);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('rejects ambiguous legacy logo flags and unsupported dimensions/format combinations',()=>{expect(()=>validateArguments(native('get_logo_url'),{identifier:'example.test',width:0})).toThrow();});
 it('reports profile method presence without values or private paths',async()=>{const s=await setup();try{const r=await call(s,'list_accounts',{});expect(JSON.stringify(r)).not.toContain('fixture-api-secret');expect(JSON.stringify(r)).not.toContain('fixture-client');expect(r.value.accounts[0]).toMatchObject({name:'default',brandApiAuth:'api_key',logoClientIdConfigured:true});expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('previews native search without credentials, query-template bug or network',async()=>{const s=await setup({BRANDFETCH_API_KEY:'',BRANDFETCH_CLIENT_ID:''});try{const r=await call(s,'preview_operation',{operation:'searchBrands',arguments:{name:'A & B'}});expect(r.value.path).toBe('/v2/search/A%20%26%20B');expect(r.value.localOnly).toBe(true);expect(r.value.searchClientIdAddedAtExecution).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('compares bounded ordered profiles and stops after failure with earlier results',async()=>{let n=0;const s=await setup({},()=>++n===2?new Response(JSON.stringify({message:'quota exceeded'}),{status:429}):new Response(JSON.stringify(data)));try{const r=await call(s,'compare_brands',{identifiers:['first.test','second.test','third.test']});expect(r.error).toBe(true);expect(exitCodeFor(r.value)).toBe(7);expect(r.value.error).toContain('first.test');expect(r.value.error).toContain('third.test');expect(s.calls).toHaveLength(2);}finally{await s.close();}});
 it('prevalidates the entire comparison before making its first request',async()=>{const s=await setup();try{expect((await call(s,'compare_brands',{identifiers:['first.test','..']})).error).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('refuses duplicate or oversized comparisons',()=>{for(const identifiers of[['a','a'],['a','b','c','d','e','f']])expect(()=>validateArguments(native('compare_brands'),{identifiers})).toThrow();});
 it('download without approval refuses before directory inspection or brand lookup',async()=>{const s=await setup();try{expect((await call(s,'download_brand_logos',{identifier:'example.test',output_dir:'/not-used'})).error).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('downloads approved original assets with no API key forwarded and private files',async()=>{const dir=await realpath(await mkdtemp(join(tmpdir(),'brandfetch-download-')));await chmod(dir,0o700);const s=await setup({},u=>u.hostname==='cdn.brandfetch.io'?new Response('<svg xmlns="http://www.w3.org/2000/svg"/>',{headers:{'content-type':'image/svg+xml'}}):new Response(JSON.stringify(data)));try{const r=await call(s,'download_brand_logos',{identifier:'example.test',output_dir:dir,confirm:true});expect(r.error).toBe(false);expect(r.value.downloaded).toBe(1);expect(await readFile(r.value.files[0].path,'utf8')).toContain('<svg');expect((s.calls[1].options.headers as any).Authorization).toBeUndefined();expect(s.calls[1].options.redirect).toBe('error');expect(JSON.stringify(r)).not.toContain('fixture-asset-secret');if(process.platform!=='win32')expect((await lstat(r.value.files[0].path)).mode&0o777).toBe(0o600);}finally{await s.close();}});
 it('refuses unsafe or absent output directories before any lookup',async()=>{const s=await setup();try{for(const output_dir of['relative','/does-not-exist'])expect((await call(s,'download_brand_logos',{identifier:'example.test',output_dir,confirm:true})).error).toBe(true);expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('never accepts Logo API hotlinks, hostile hosts, userinfo or duplicated c',async()=>{const s=await setup();try{for(const src of['https://cdn.brandfetch.io/domain/example.test?c=client','https://evil.test/id_fixture/logo.svg?c=x','https://key@cdn.brandfetch.io/id_fixture/logo.svg?c=x','https://cdn.brandfetch.io/id_fixture/logo.svg?c=a&c=b','https://cdn.brandfetch.io/id_fixture/logo.svg'])expect(()=>s.api.validateAssetUrl(src)).toThrow();expect(s.calls).toHaveLength(0);}finally{await s.close();}});
 it('stops download on unsupported MIME and reports reserved file without credentials',async()=>{const dir=await realpath(await mkdtemp(join(tmpdir(),'brandfetch-mime-')));await chmod(dir,0o700);const s=await setup({},u=>u.hostname==='cdn.brandfetch.io'?new Response('not image',{headers:{'content-type':'text/html'}}):new Response(JSON.stringify(data)));try{const r=await call(s,'download_brand_logos',{identifier:'example.test',output_dir:dir,confirm:true});expect(r.error).toBe(true);expect(r.value.error).toContain('reservedFile');expect(r.value.error).not.toContain('fixture-asset-secret');expect(s.calls).toHaveLength(2);}finally{await s.close();}});
 it('uses fresh exclusive filenames and never overwrites an existing file',async()=>{const dir=await realpath(await mkdtemp(join(tmpdir(),'brandfetch-exclusive-')));await chmod(dir,0o700);await writeFile(join(dir,'existing.svg'),'keep');const s=await setup({},u=>u.hostname==='cdn.brandfetch.io'?new Response('<svg/>',{headers:{'content-type':'image/svg+xml'}}):new Response(JSON.stringify(data)));try{const a=await call(s,'download_brand_logos',{identifier:'example.test',output_dir:dir,confirm:true}),b=await call(s,'download_brand_logos',{identifier:'example.test',output_dir:dir,confirm:true});expect(a.value.files[0].path).not.toBe(b.value.files[0].path);expect(await readFile(join(dir,'existing.svg'),'utf8')).toBe('keep');}finally{await s.close();}});
});
describe('bounded failures with no automatic request replay',()=>{
 for(const[status,exit,detail]of[[401,4,'invalid key'],[403,7,'quota exceeded'],[404,3,'not found'],[429,7,'rate limit'],[500,5,'upstream failure']]as const)it('classifies '+status+' with one request and sanitized errors',async()=>{const s=await setup({},()=>new Response(JSON.stringify({message:detail,api_key:'fixture-api-secret',src:assetSrc}),{status}));try{const r=await call(s,'get_brand',{identifier:'example.test'});expect(r.error).toBe(true);expect(exitCodeFor(r.value)).toBe(exit);expect(s.calls).toHaveLength(1);expect(JSON.stringify(r)).not.toContain('fixture-api-secret');expect(JSON.stringify(r)).not.toContain('fixture-asset-secret');}finally{await s.close();}});
 it('network failures do not expose raw error contents or replay',async()=>{const s=await setup({},()=>{throw Error('fixture-api-secret '+assetSrc);});try{const r=await call(s,'get_brand',{identifier:'example.test'});expect(r.error).toBe(true);expect(r.value.error).toContain('No automatic retry'.toLowerCase());expect(JSON.stringify(r)).not.toContain('fixture-api-secret');expect(s.calls).toHaveLength(1);}finally{await s.close();}});
 it('rejects oversized streamed provider responses without replay',async()=>{const s=await setup({},()=>new Response('x'.repeat(5*1048576+1)));try{expect((await call(s,'get_brand',{identifier:'example.test'})).error).toBe(true);expect(s.calls).toHaveLength(1);}finally{await s.close();}});
});
