import{open,lstat}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{BrandfetchError,UsageError}from'./errors.js';
export type Json=Record<string,any>;export type QueryParam={name:string;value:unknown};
const CDN='cdn.brandfetch.io',MAX=5*1048576;
export class BrandfetchClient{
 private tokens=new Map<string,string>();private privateUrls=new Set<string>();private schedules=new Map<string,Promise<void>>();private nextAt=new Map<string,number>();
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.map(a=>a.apiToken),...this.tokens.values(),...this.privateUrls].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]').replace(/https:\/\/cdn\.brandfetch\.io\/[^\s"<>]*\?[^\s"<>]*\bc=[^\s"<>]+/gi,u=>{try{const c=new URL(u).searchParams.get('c');return this.config.accounts.some(a=>a.clientId&&a.clientId===c)?u:'[private asset URL]';}catch{return'[private asset URL]';}});}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|signing_key|api_token|token|access_token|refresh_token|authorization|client_secret)$/i.test(k)||(/^api_key$/i.test(k)&&typeof x==='string')?'[redacted]':this.sanitize(x)]));return v;}
 private learnUrls(v:unknown){if(Array.isArray(v)){v.forEach(x=>this.learnUrls(x));return;}if(v&&typeof v==='object')for(const[k,x]of Object.entries(v)){if(k==='src'&&typeof x==='string'){try{const u=new URL(x);if(u.hostname===CDN&&u.search)this.privateUrls.add(x);}catch{}}else this.learnUrls(x);}}
 private async token(a:Account){if(this.tokens.has(a.name))return this.tokens.get(a.name)!;let token=a.apiToken;if(a.tokenFile){let file;try{if(!isAbsolute(a.tokenFile))throw Error();if(!(await lstat(a.tokenFile)).isFile())throw Error();file=await open(a.tokenFile,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await file.readFile('utf8')).trim();}catch{throw new BrandfetchError('Cannot read the private Brandfetch token file; use an absolute owner-only regular token-only file at most 64 KiB.',0,'CONFIG');}finally{await file?.close();}}if(!token||/[\r\n]/.test(token))throw new BrandfetchError('No valid API key configured for the selected profile. Run brandfetch-cli login.',0,'CONFIG');this.tokens.set(a.name,token);return token;}
 private async pace(a:Account){const prior=this.schedules.get(a.name)??Promise.resolve();const next=prior.catch(()=>{}).then(async()=>{const delay=Math.max(0,(this.nextAt.get(a.name)??0)-Date.now());if(delay)await this.sleep(delay);this.nextAt.set(a.name,Date.now()+this.config.minIntervalMs);});this.schedules.set(a.name,next);await next;}
 private async bytes(response:Response){const chunks:Uint8Array[]=[];let total=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX){await reader.cancel();throw new BrandfetchError('Response exceeds the 5 MiB local cap; no automatic retry.');}chunks.push(part.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
 async request(method:string,path:string,query:QueryParam[]=[],body?:Json,hint?:string,rawResult=false):Promise<Json>{
  // Only current fixed routes. Encoded slashes inside URL/email identifiers are legitimate.
  if(!['GET','HEAD','POST'].includes(method)||!/^\/(?:brands\/(?:domain\/|ticker\/|isin\/|crypto\/)?[^/]+|context\/[^/]+|search\/[^/]+|viewer)$/.test(path)||/^[^?]*\?/.test(path)||path.split('/').some(s=>s==='.'||s==='..'||/^(?:%2e){1,2}$/i.test(s)))throw new UsageError('Unsupported Brandfetch API path.');
  if(method==='POST'&&path!=='/brands/transaction'||method==='HEAD'&&!/^\/brands\/(?:domain\/)?[^/]+$/.test(path))throw new UsageError('Unsupported Brandfetch API method.');
  const a=selectAccount(this.config,hint),search=path.startsWith('/search/'),url=new URL('/v2'+path,'https://api.brandfetch.io');
  for(const p of query){if(p.value!==undefined){if(typeof p.value==='object')throw new UsageError('Unsupported object query parameter.');url.searchParams.set(p.name,String(p.value));}}
  const headers:Record<string,string>={Accept:'application/json'};
  if(search){if(!a.clientId)throw new BrandfetchError('No client ID configured for the selected profile. Run brandfetch-cli login.',0,'CONFIG');url.searchParams.set('c',a.clientId);}else headers.Authorization='Bearer '+await this.token(a);
  const encoded=body===undefined?undefined:JSON.stringify(body);if(encoded!==undefined){if(Buffer.byteLength(encoded)>1048576)throw new UsageError('Request exceeds 1 MiB JSON limit.');headers['Content-Type']='application/json';}
  await this.pace(a);let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers,...(encoded===undefined?{}:{body:encoded})});}catch{throw new BrandfetchError('Brandfetch request failed or timed out. Its outcome may be unknown; no automatic retry. Inspect provider state before deliberately repeating.',0,'NETWORK');}
  const text=(await this.bytes(response)).toString('utf8');if(!response.ok){let detail='';try{const parsed=JSON.parse(text);this.learnUrls(parsed);detail=JSON.stringify(this.sanitize(parsed)).slice(0,1000);}catch{}const quota=response.status===429||response.status===402||response.status===403&&/quota|credit|limit/i.test(detail);throw new BrandfetchError('Brandfetch API '+response.status+(quota?' quota exceeded':'')+(detail?': '+detail:''),response.status,quota?'RATE_LIMIT':response.status===401||response.status===403?'AUTH':'API_ERROR');}
  if(method==='HEAD')return{status:response.status,crawlQueued:response.status===202,indexed:response.status===200,retryAfter:response.headers.get('retry-after')};
  if(response.status===204)return{status:204,cachedMiss:true,data:null};
  let parsed;try{parsed=JSON.parse(text);}catch{throw new BrandfetchError('Brandfetch returned a non-JSON response.');}if(parsed===null||typeof parsed!=='object')throw new BrandfetchError('Invalid Brandfetch JSON response.');this.learnUrls(parsed);return(rawResult?parsed:this.sanitize(parsed))as Json;
 }
 validateAssetUrl(src:string){try{const u=new URL(src);if(u.protocol!=='https:'||u.hostname!==CDN||u.username||u.password||u.port||u.hash||!/^\/id[A-Za-z0-9_-]+\//.test(u.pathname)||u.pathname.includes('..')||/%2e|%2f|%5c/i.test(u.pathname)||u.searchParams.size!==1||!u.searchParams.get('c'))throw Error();this.privateUrls.add(src);return u;}catch{throw new UsageError('Asset URL must be an original credentialed Brand API asset src on the allowed CDN, with one nonempty c parameter. Browser Logo API hotlinks cannot be downloaded.');}}
 async asset(src:string,hint?:string){const url=this.validateAssetUrl(src),a=selectAccount(this.config,hint);await this.pace(a);let response:Response;try{response=await this.fetcher(url,{method:'GET',redirect:'error',signal:AbortSignal.timeout(Math.min(this.config.timeoutMs,5000)),headers:{Accept:'image/*'}});}catch{throw new BrandfetchError('Private asset fetch failed, redirected or timed out; no automatic retry.');}if(!response.ok)throw new BrandfetchError('Brandfetch CDN '+response.status+'; use original Brand API asset credentials. No hotlink evasion or retry.',response.status);const mime=response.headers.get('content-type')?.split(';')[0]?.toLowerCase();const formats:Record<string,string>={'image/svg+xml':'svg','image/png':'png','image/jpeg':'jpeg','image/webp':'webp','image/gif':'gif'};if(!mime||!formats[mime])throw new BrandfetchError('Asset has an unsupported image Content-Type.');const bytes=await this.bytes(response);if(!bytes.length)throw new BrandfetchError('Empty asset refused.');return{bytes,mime,format:formats[mime]};}
}
