import operationsData from'./operations.json' with{type:'json'};import{Ajv2020}from'ajv/dist/2020.js';import type{ValidateFunction}from'ajv';import{open,lstat,realpath}from'node:fs/promises';import{isAbsolute,resolve,join}from'node:path';import{randomUUID,createHash}from'node:crypto';
import type{Json,BrandfetchClient}from'../api/client.js';import{UsageError,BrandfetchError}from'../api/errors.js';import type{Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";import{selectAccount}from'../config.js';
export type Operation={operationId:string;method:string;path:string;parameters:{name:string;in:string;required:boolean;schema:Json}[];bodySchema:Json;risk:Risk;responses:string[]};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:BrandfetchClient)=>Promise<unknown>};
export const OPERATIONS=operationsData as unknown as Operation[];const ajv=new Ajv2020({strict:false,allErrors:true});const validators=new Map<string,ValidateFunction>();
const str=(description:string,maxLength=2048)=>({type:'string',minLength:1,maxLength,description});const account={type:'string',description:'Exact private profile label. Never inherits another profile or global key/client ID.'};const obj=(properties:Json,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});const idFields={identifier:str('Domain, email, URL, Brand ID, ticker, ISIN or crypto symbol. Explicit types accept only their identifier format.'),identifier_type:{type:'string',enum:['auto','domain','ticker','isin','crypto'],default:'auto',description:'Explicit provider route avoids identifier collisions.'},allowNsfw:{type:'boolean',description:'Optional provider NSFW behavior; absence differs from false.'},cachedOnly:{type:'boolean',default:false,description:'True avoids crawling a cache miss; 204 is reported as cachedMiss. Indexed reads still consume quota.'},account};
function op(id:string){const o=OPERATIONS.find(o=>o.operationId===id);if(!o)throw new UsageError('Unknown native operation.');return o;}
function identifierPath(identifier:string,type='auto'){if(!identifier.trim()||/[\u0000-\u001f\u007f]/.test(identifier)||identifier.startsWith('.'))throw new UsageError('Invalid identifier.');if(type==='domain'&&!/^(?=.{1,253}$)[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?\.[a-zA-Z]{2,}$/.test(identifier))throw new UsageError('Explicit domain requires a domain, not a URL or email address.');if(['ticker','crypto'].includes(type)&&!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(identifier)||type==='isin'&&!/^[A-Z]{2}[A-Z0-9]{9}[0-9]$/.test(identifier))throw new UsageError('Invalid explicit identifier format.');return'/brands/'+(type==='auto'?'':type+'/')+encodeURIComponent(identifier);}
async function brand(a:Json,c:BrandfetchClient,raw=false){return c.request('GET',identifierPath(a.identifier,a.identifier_type),[{name:'allowNsfw',value:a.allowNsfw},{name:'cachedOnly',value:a.cachedOnly}],undefined,a.account,raw);}
const ALL:ToolSpec[]=[];
function tool(name:string,title:string,description:string,group:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL.push({name,title,description,group,risk,inputSchema:obj(properties,required),handler});}
tool('get_brand','Get brand data','Current Brand API V2 data through generic or explicit routes. One request; credentialed asset src URLs are redacted from output. Provider reads may spend quota or crawl on a miss.','Brand reads','read',idFields,['identifier'],brand);
tool('search_brands','Search brands','Search by name with the selected profile client ID in native query c. No Brand API Bearer key sent. One request; no pagination or retries.','Brand reads','read',{query:str('Brand name to search.',512),account},['query'],(a,c)=>c.request('GET','/search/'+encodeURIComponent(a.query),[],undefined,a.account));
tool('get_brand_context','Get interpreted brand context','One Brand Context API request. Context is probabilistic interpretation, not verified company facts. Accepts domain/email/URL; cachedOnly avoids crawling a miss.','Brand reads','read',{domain:str('Domain, URL or email address.'),cachedOnly:idFields.cachedOnly,account},['domain'],(a,c)=>{if(['.','..'].includes(a.domain)||/[\u0000-\u001f\u007f]/.test(a.domain))throw new UsageError('Invalid context identifier.');return c.request('GET','/context/'+encodeURIComponent(a.domain),[{name:'cachedOnly',value:a.cachedOnly}],undefined,a.account);});
tool('enrich_transaction','Enrich a transaction descriptor','Resolve the user-requested transaction label into brand data. Sends the label and country to Brandfetch and may consume credits; does not create a charge, bank connection or payment.','Brand reads','read',{transaction_label:str('Only the specific transaction label requested by the user.',4096),country_code:{type:'string',pattern:'^[A-Z]{2}$',description:'ISO 3166-1 alpha-2 country code, uppercase.'},account},['transaction_label','country_code'],(a,c)=>c.request('POST','/brands/transaction',[],{transactionLabel:a.transaction_label,countryCode:a.country_code},a.account));
tool('get_viewer','Verify Brand API identity','GET /v2/viewer using the selected private Brand API key. Returns provider viewer metadata; does not purchase access or expose the key.','Brand reads','read',{account},[],(a,c)=>c.request('GET','/viewer',[],undefined,a.account));
tool('prefetch_brand','Prefetch a brand','Explicitly confirmed HEAD request can enqueue a provider crawl. Generic or domain route only. Return 200 indexed / 202 crawl queued; never poll, purchase or resubmit automatically.','Confirmed operations','destructive',{identifier:idFields.identifier,identifier_type:{type:'string',enum:['auto','domain'],default:'auto'},account,confirm:{type:'boolean',description:'Must be true for this exact provider crawl request.'}},['identifier'],(a,c)=>c.request('HEAD',identifierPath(a.identifier,a.identifier_type),[],undefined,a.account));
for(const noun of['colors','fonts'])tool('get_brand_'+noun,'Get brand '+noun,'One native brand read with only name, domain and '+noun+' returned. Filtering is local: provider quota and crawling behavior are unchanged.','Focused reads','read',idFields,['identifier'],async(a,c)=>{const d=await brand(a,c);if(d.cachedMiss===true)return d;return{name:d.name,domain:d.domain,[noun]:d[noun]??[]};});
tool('compare_brands','Compare brands','Read two to five unique identifiers sequentially in one exact profile, preserving input order. Return colors/fonts/logo counts; stop at the first failure with completed results. No retries, cross-account mixing or complete-market claim.','Focused reads','read',{identifiers:{type:'array',minItems:2,maxItems:5,uniqueItems:true,items:idFields.identifier,description:'Two to five distinct identifiers in requested order.'},identifier_type:idFields.identifier_type,allowNsfw:idFields.allowNsfw,cachedOnly:idFields.cachedOnly,account},['identifiers'],async(a,c)=>{a.identifiers.forEach((s:string)=>identifierPath(s,a.identifier_type));selectAccount(c.config,a.account);const results:Json[]=[];for(let i=0;i<a.identifiers.length;i++){try{const d=await brand({...a,identifier:a.identifiers[i]},c);results.push(d.cachedMiss===true?{identifier:a.identifiers[i],...d}:{identifier:a.identifiers[i],name:d.name,domain:d.domain,colors:d.colors??[],fonts:d.fonts??[],logoCount:Array.isArray(d.logos)?d.logos.length:0,qualityScore:d.qualityScore});}catch(e){const err=e as BrandfetchError;throw new BrandfetchError(JSON.stringify(c.sanitize({notice:'Comparison stopped; earlier reads may have consumed quota.',completed:results,failedIdentifier:a.identifiers[i],remaining:a.identifiers.slice(i+1),error:err.message})),err.status,err.code);}}return{complete:true,requests:results.length,results};});
tool('get_logo_url','Build a browser logo URL','Local Logo API URL construction with the selected profile client ID. Direct browser display only; programmatic fetching these hotlinks is prohibited/blocked. No provider call or automatic download.','Local','read',{identifier:idFields.identifier,identifier_type:{type:'string',enum:['domain','ticker','isin','crypto'],default:'domain'},type:{type:'string',enum:['icon','logo','symbol'],default:'logo',description:'Explicit asset type; separate from identifier_type.'},icon:{type:'boolean',description:'Legacy compatibility: true selects icon. Do not combine with type.'},width:{type:'integer',minimum:1,maximum:2048},height:{type:'integer',minimum:1,maximum:2048},theme:{type:'string',enum:['light','dark']},fallback:{type:'string',enum:['brandfetch','transparent','lettermark','404'],default:'404'},format:{type:'string',enum:['png','jpeg','webp','svg'],description:'SVG allowed only for logo or symbol.'},account},['identifier'],async(a,c)=>{const profile=selectAccount(c.config,a.account);if(!profile.clientId)throw new BrandfetchError('No client ID configured for the selected profile. Run brandfetch-cli login.',0,'CONFIG');if(a.icon!==undefined&&a.type!==undefined)throw new UsageError('Use icon or type, not both.');const type=a.icon===true?'icon':a.type??'logo',idType=a.identifier_type??'domain';identifierPath(a.identifier,idType);if(a.fallback==='lettermark'&&type!=='icon'||a.format==='svg'&&type==='icon')throw new UsageError('Invalid logo fallback or format for selected type.');let path='/'+idType+'/'+encodeURIComponent(a.identifier);for(const[key,value]of[['w',a.width],['h',a.height],['theme',a.theme],['fallback',a.fallback??'404'],['type',type]])if(value!==undefined)path+='/'+key+'/'+value;if(a.format)path+='.'+a.format;const url=new URL(path,'https://cdn.brandfetch.io');url.searchParams.set('c',profile.clientId);return{url:url.href,browserDisplayOnly:true,programmaticDownloadAllowed:false,notice:'For private local assets, use download_brand_logos with a Brand API key, not this client-ID hotlink.'};});
async function privateDirectory(path:string){try{if(!isAbsolute(path))throw Error();const s=await lstat(path),actual=await realpath(path);if(!s.isDirectory()||process.platform!=='win32'&&(s.uid!==process.getuid?.()||(s.mode&0o077))||(process.platform==='win32'?actual.toLowerCase()!==resolve(path).toLowerCase():actual!==resolve(path)))throw Error();return actual;}catch{throw new UsageError('Private output directory must already exist at a canonical absolute path, with owner-only permissions. Windows ACLs must be restricted by the owner. No automatic directory creation.');}}
tool('download_brand_logos','Download private brand logos','Confirmed one brand lookup plus at most five original credentialed Brand API logo src downloads. Owner-private directory and exclusive files only; cap 5 MiB each, fixed CDN, no redirects/Bearer forwarding/hotlink evasion/retries. Stop on failure, retain and report completed/reserved files.','Confirmed operations','destructive',{...idFields,output_dir:str('Existing canonical absolute owner-private directory.'),format_preference:{type:'string',enum:['svg','png','all'],default:'all'},max_files:{type:'integer',minimum:1,maximum:5,default:3},confirm:{type:'boolean',description:'Approve exactly this provider lookup and bounded private local downloads.'}},['identifier','output_dir'],async(a,c)=>{const directory=await privateDirectory(a.output_dir);identifierPath(a.identifier,a.identifier_type);selectAccount(c.config,a.account);const d=await brand(a,c,true);if(d.cachedMiss===true)return d;const validFormats=['svg','png','jpeg','jpg','webp','gif'];const found=(Array.isArray(d.logos)?d.logos:[]).flatMap((logo:Json)=>(Array.isArray(logo.formats)?logo.formats:[]).map((f:Json)=>({logo,f}))).filter(({f}:{f:Json})=>validFormats.includes(f.format)&&(a.format_preference===undefined||a.format_preference==='all'||f.format===a.format_preference));const selected=found.slice(0,a.max_files??3);for(const{f}of selected)c.validateAssetUrl(f.src);const files:Json[]=[];for(const{logo,f}of selected){const path=join(directory,'brandfetch-'+randomUUID()+'.'+(f.format==='jpg'?'jpeg':f.format));let output;try{output=await open(path,'wx',0o600);const asset=await c.asset(f.src,a.account);if(asset.format!==(f.format==='jpg'?'jpeg':f.format))throw new BrandfetchError('Asset Content-Type does not match its declared provider format.');await output.writeFile(asset.bytes);await output.sync();files.push({path,format:asset.format,type:logo.type,theme:logo.theme,bytes:asset.bytes.length,sha256:createHash('sha256').update(asset.bytes).digest('hex')});}catch(e){const err=e as BrandfetchError;throw new BrandfetchError(JSON.stringify(c.sanitize({notice:'Download stopped. Completed files are retained. A reserved file may be empty or incomplete; inspect it privately before repeating. No automatic retry.',files,reservedFile:output?path:null,error:err.message})),err.status??0,err.code??'API_ERROR');}finally{await output?.close();}}return{brand:d.name,files,downloaded:files.length,availableMatching:found.length,limitReached:found.length>selected.length,credentialUrlsReturned:false};});
tool('list_accounts','List private profiles','Local labels, default and credential method availability only. No keys, client IDs, private paths or network.','Local','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,brandApiAuth:a.tokenFile?'token_file':a.apiToken?'api_key':'not_configured',logoClientIdConfigured:!!a.clientId}))}));
tool('get_operation_schema','Inspect a native operation','Complete pinned Brandfetch path/query/body schema and documented response statuses for one of 11 supported native operations. Local only; agent purchases excluded.','Local','read',{operation:{type:'string',enum:OPERATIONS.map(o=>o.operationId)}},['operation'],async a=>op(a.operation));
function nativeArgs(o:Operation){return obj({...Object.fromEntries(o.parameters.filter(p=>p.name!=='c').map(p=>[p.name,p.schema])),...(Object.keys(o.bodySchema).length?{payload:o.bodySchema}:{}),account},[...o.parameters.filter(p=>p.required&&p.name!=='c').map(p=>p.name),...(Object.keys(o.bodySchema).length?['payload']:[])]);}
// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const nativeValidators=new Map<string,ValidateFunction<Json>>();
function nativeValidator(o:Operation){let v=nativeValidators.get(o.operationId);if(!v){v=ajv.compile<Json>(nativeArgs(o));nativeValidators.set(o.operationId,v);}return v;}
tool('preview_operation','Preview a native request','Validate one exact native operation request locally, without loading keys/client IDs, contacting Brandfetch, reserving files or claiming provider validation or price. Search c is added from private profile at execution.','Local','read',{operation:{type:'string',enum:OPERATIONS.map(o=>o.operationId)},arguments:{type:'object',description:'Native path/query arguments and transaction payload. Inspect get_operation_schema first.'}},['operation','arguments'],async(a,c)=>{const o=op(a.operation),v=nativeValidator(o);if(!v(a.arguments))throw new UsageError(ajv.errorsText(v.errors));let path=o.path;for(const p of o.parameters.filter(p=>p.in==='path')){const s=String(a.arguments[p.name]);if(['.','..'].includes(s)||/[\u0000-\u001f\u007f]/.test(s))throw new UsageError('Invalid native identifier.');path=path.replace('{'+p.name+'}',encodeURIComponent(s));}return{operation:o.operationId,method:o.method,path,query:Object.fromEntries(o.parameters.filter(p=>p.in==='query'&&p.name!=='c'&&a.arguments[p.name]!==undefined).map(p=>[p.name,a.arguments[p.name]])),payload:a.arguments.payload,profile:a.arguments.account??c.config.defaultAccount??null,requiresConfirmation:o.risk!=='read',localOnly:true,providerValidated:false,quotaCalculated:false,searchClientIdAddedAtExecution:o.operationId==='searchBrands'};});
export const ALL_TOOLS=ALL;
function validatorFor(t:ToolSpec){let v=validators.get(t.name);if(!v){v=ajv.compile(t.inputSchema);validators.set(t.name,v);}return v;}
export function validateArguments(t:ToolSpec,a:Json){const v=validatorFor(t);if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
/** Compile every input and native schema, as loading once did, so a test can prove they all compile. */
export function compileAll(){for(const t of ALL_TOOLS)validatorFor(t);for(const o of OPERATIONS)nativeValidator(o);return validators.size+nativeValidators.size;}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
